// <auto-generated />
using BakeryWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BakeryWebsite.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20201204061316_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BakeryWebsite.Models.Clients", b =>
                {
                    b.Property<int>("clientsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("clCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clPostalcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orderID")
                        .HasColumnType("int");

                    b.HasKey("clientsID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("BakeryWebsite.Models.Orders", b =>
                {
                    b.Property<int>("ordersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ordDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ordDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ordQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productID")
                        .HasColumnType("int");

                    b.HasKey("ordersID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("BakeryWebsite.Models.Products", b =>
                {
                    b.Property<int>("productsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("prdDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prdPrice")
                        .HasColumnType("int");

                    b.HasKey("productsID");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
